export const portfolioSlides = [
    {
        title: 'accountant services',
        date: '01.08.2024 - 01.09.2024',
        image: '/img/portfolio/accountant-services.webp',
        companyBudget: '$3 108',
        averageLeadPrice: '$33,4',
        numberOfLeads: '93',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v10',
    },
    {
        title: 'beauty salon',
        date: '04.01.2024 - 4.02.2024',
        image: '/img/portfolio/beauty-salon.webp',
        companyBudget: '',
        averageLeadPrice: '',
        numberOfLeads: '218',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v1',
    },
    {
        title: 'beauty salon 2',
        date: '02.03.2024 - 02.04.2024',
        image: '/img/portfolio/beauty-salon-2.webp',
        companyBudget: '£3 836',
        averageLeadPrice: '£27,4',
        numberOfLeads: '142',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v2',
    },
    {
        title: 'Car Detaling',
        date: '04.03.2024 - 4.04.2024',
        image: '/img/portfolio/car-detaling.webp',
        companyBudget: '13 908 PLN',
        averageLeadPrice: '183 PLN',
        numberOfLeads: '76',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v3',
    },
    {
        title: 'real estate',
        date: '03.03.2024 - 03.04.2024',
        image: '/img/portfolio/real-estate.webp',
        companyBudget: '$4 348',
        averageLeadPrice: '$45,7',
        numberOfLeads: '95',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v4',
    },
    {
        title: 'inferior designer',
        date: '01.05.2024 - 31.05.2024',
        image: '/img/portfolio/inferior-designer.webp',
        companyBudget: '',
        averageLeadPrice: '',
        numberOfLeads: '100',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v5',
    },
    {
        title: 'home improvement',
        date: '01.05.2024 - 31.05.2024',
        image: '/img/portfolio/home-improvement.webp',
        companyBudget: '',
        averageLeadPrice: '',
        numberOfLeads: '',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v6',
    },
    {
        title: 'e-commerce',
        date: '01.04.2024 - 01.06.2024',
        image: '/img/portfolio/e-commerce.webp',
        companyBudget: '$9 569',
        averageLeadPrice: '$7.06',
        numberOfLeads: '1 354',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v7',
    },
    {
        title: 'roofing',
        date: '03.04.2024 - 03.05.2024',
        image: '/img/portfolio/roofing.webp',
        companyBudget: '$4 313',
        averageLeadPrice: '120',
        numberOfLeads: '18',
        numberOfSales: '$239,6',
        costPerSale: '',
        slug: '/v8',
    },
    {
        title: 'INTERIOR DESIGNER',
        date: '01.05.2024 - 31.05.2024',
        image: '/img/portfolio/accountant-services.webp',
        companyBudget: '',
        averageLeadPrice: '$214,94',
        numberOfLeads: '',
        numberOfSales: '',
        costPerSale: '',
        slug: '/v9',
    },
];